[package]
name = "gitehr"
version = "0.1.5"
edition = "2024"
description = "A Git-based Electronic Health Record system"
authors = ["Marcus Baw"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
fs_extra = "1.3"
uuid = { version = "1.19", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10"
rand = "0.8"

[dev-dependencies]
tempfile = "3.24"
regex = "1.12"
