[package]
name = "gitehr"
version = "0.1.6"
edition = "2024"
description = "A Git-based Electronic Health Record system"
authors = ["Marcus Baw"]

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
anyhow = "1.0.100"
fs_extra = "1.3.0"
uuid = { version = "1.19.0", features = ["v4"] }
chrono = { version = "0.4.43", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
sha2 = "0.10.9"
rand = "0.9.2"

[dev-dependencies]
tempfile = "3.24.0"
regex = "1.12.2"
