[package]
name = "gitehr"
version = "0.1.7"
edition = "2024"
description = "A Git-based Electronic Health Record system"
authors = ["Marcus Baw"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
fs_extra = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"
sha2 = "0.10"
rand = "0.9"
which = "8.0"
walkdir = "2.5"
tar = "0.4"
flate2 = "1.0"

[dev-dependencies]
tempfile = "3"
regex = "1"
serial_test = "3"
